version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - 8080
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "whether_db"
      POSTGRES_USER: "whether_user"
      POSTGRES_PASSWORD: "whether_password183!!945643"
    expose:
      - 5432
